<?php $this->widget('EExcelView',array(
    'id'=>'invoice-his-grid',
    'fixedHeader' => true,
    //'responsiveTable' => true,
    'type'=>TbHtml::GRID_TYPE_BORDERED,
    'template'=>"{summary}\n{items}\n{exportbuttons}\n{pager}",
    'dataProvider'=>$model->buyingHis($client_id,'='),
    'summaryText' =>'<p class="text-info"> Buying History </p>',
    'htmlOptions'=>array('class'=>'table-responsive panel'),
    'columns'=>array(
        array('name'=>'purchased_at',
            'header'=>Yii::t('app','Date Purchased'),
            'value'=>'$data["purchased_at"]',
            'type'=>'raw',
        ),
        array('name'=>'ticket_number',
            'header'=>Yii::t('app','Ticket Number'),
        ),
        array('name'=>'unit_price',
            'header'=>Yii::t('app','Price'),
        ),
        array('name'=>'client_name',
            'header'=>Yii::t('app','Sold To'),
            'value'=>'$data["client_name"]',
        ),
    ),
));