<?php
	$cs = Yii::app()->getClientScript();
	$cs->registerScriptFile(baseurl().'/js/vue.js',CClientScript::POS_BEGIN);
    $cs->registerScriptFile(baseurl().'/js/vuetify.js',CClientScript::POS_BEGIN);
    $cs->registerScriptFile(baseurl().'/js/axios.js',CClientScript::POS_BEGIN);
    $baseUrl=Yii::app()->baseUrl;
?>
<script type="text/javascript">
	//var last7dayUrl=<?=$baseUrl.'/raffle/GetResult7day'?>
	//alert(last7dayUrl)
	new Vue({
        el: '#app' ,
        data(){
            return{
                hide:false,
                dialog:false,
                dialog2:false,
                dialog3:true,
                credit:1000,
                price:0,
                betAmount:10,
                spinNumber:0,
                spining:false,
                luckyDraw:[
                    {"price":"100","luckyNum":"6798"},{"price":"100","luckyNum":"7831"}
                ], //should return value from database
                current:'',
                links: ['Home', 'About Us', 'Team', 'Services', 'Contact Us'],
                menus:[
                    {text:'Online Casino',link:'http://localhost/bakou-raffle/index.php/Raffle/OnlineCasino'},
                    {text:'Online Sport',link:'http://localhost/bakou-raffle/index.php/Raffle/OnlineSport'},
                    {text:'Online Lottery',link:'http://localhost/bakou-raffle/index.php/Raffle/OnlineLottery'},
                    {text:'Online Raffle',link:'#'},
                    {text:'Promotion',link:'http://localhost/bakou-raffle/index.php/Raffle/Promotion/'},
                    {text:'Raffle Result',link:'#'},
                ],
                fmenus:[
                    {text:'หน้าหลัก',link:'http://www.winwin97.com/'},
                    {text:'คาสิโนออนไลน์',link:'http://www.winwin97.com/casino/'},
                    {text:'สปอร์ตออนไลน์',link:'http://www.winwin97.com/sport/'},
                    {text:'หวยออนไลน์',link:'http://www.winwin97.com/lotto/'},
                    {text:'สมัครสมาชิก',link:'http://www.winwin97.com/register/'},
                    {text:'โปรโมชั่น',link:'http://www.winwin97.com/promotion/'},
                    {text:'แจ้งฝาก – แจ้งถอน',link:'http://www.winwin97.com/banking/'},
                    {text:'LIVE SCORE',link:'http://www.winwin97.com/live-score/'},
                    {text:'ติดต่อเรา',link:'http://www.winwin97.com/contact/'},
                ],
                items: [
                    { src: 'http://www.winwin97.com/wp-content/uploads/2017/03/slide02.jpg' },
                    { src: 'http://www.winwin97.com/wp-content/uploads/2017/03/slide03.jpg?v=1.0' },
                    { src: 'http://www.winwin97.com/wp-content/uploads/2017/03/slide04.jpg?v=1.0' }
                ],
                lotteries:[],
								menu1: null,
								menu2: null,
								clientHistory: [],
								start_date: null,
								end_date: null
            }
        },
        created(){
            this.Spin()
            this.insertLuckyNumber(0)
            this.getLast7DaysResult();

						var d = new Date();
    				this.start_date = d.getFullYear() + '-' + (d.getMonth() < 10 ? '0' + d.getMonth() : d.getMonth()) + '-' + d.getDate()
						this.end_date = d.getFullYear() + '-' + (d.getMonth() < 10 ? '0' + d.getMonth() : d.getMonth()) + '-' + d.getDate()
        },
        watch:{
            price:function(){
                if(this.price>0){
                    this.betAmount=this.price
                }else if(parseInt(this.price)>parseInt(this.credit)){
                    this.dialog=true
                }
            }
        },
        methods:{
            getLast7DaysResult(){
                var vm=this
                axios.get('<?php echo Yii::app()->createUrl('/raffle/GetResult7day')?>')
                  .then(function (response) {
                    vm.lotteries=response.data;
                  })
                  .catch(function (error) {
                    console.log(error);
                  });
            },
            Spin:function(){
                var vm=this
                vm.spining=!vm.spining
                var spiningRun=setInterval(function(){
                    if(vm.spining==true){
                        vm.spinNumber=Math.random().toString().slice(2,6) //This number are generated by db already?
                    }else{
                        clearInterval(spiningRun)
                    }
                },100);
            },
            bet(){
                if(parseInt(this.betAmount)>0 & parseInt(this.betAmount)<=parseInt(this.credit)){
                    this.credit=parseInt(this.credit)-parseInt(this.betAmount)
                    this.betAmount=this.price
                    this.price=0
                }else{
                    this.credit=parseInt(this.credit)
                }
            },
            insertLuckyNumber(act){ //this is will use sql/database instead

            	var vm=this
                axios.get('<?php echo Yii::app()->createUrl('/raffle/PickupTicket?act=')?>'+act)
                  .then(function (response) {
                    vm.luckyDraw=response.data.result;
                    vm.credit=response.data.balance;
                  })
                  .catch(function (error) {
                    console.log(error);
                  });

                // if(this.credit>0){
                //     this.credit=parseInt(this.credit)-parseInt(this.betAmount)
                //     this.luckyDraw.push({price:this.betAmount,luckyNum:this.spinNumber})
                // }else{

                // }

            },
            resetAmount(){
                this.price=this.credit
                this.dialog=false;
            },
						getClientHistory(){
							var vm = this
							axios.get('<?php echo Yii::app()->createUrl('/raffle/GetClientHistory?sdate=')?>'+vm.start_date + '&edate=' + vm.end_date)
								.then(function (response) {
									vm.clientHistory = response.data
								})
								.catch(function (error) {
									console.log(error);
								});
						}
        }
    })
</script>
